# permissions for end users to view jupyters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyter-viewer-role
rules:
- apiGroups:
  - operators.convect.ai
  resources:
  - jupyters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.convect.ai
  resources:
  - jupyters/status
  verbs:
  - get
