
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - operators.convect.ai
  resources:
  - jupyters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.convect.ai
  resources:
  - jupyters/finalizers
  verbs:
  - update
- apiGroups:
  - operators.convect.ai
  resources:
  - jupyters/status
  verbs:
  - get
  - patch
  - update
